In [3]:
# Importing libraries
import pandas as pd
import numpy as np
import math
import operator
import numpy
import sklearn
import scipy
from sklearn.preprocessing import MinMaxScaler

In [4]:
#### Start of STEP 1
# Importing data 
data = pd.read_csv("iris_V2.csv")
#### End of STEP 1

array = data.values
# separate array into input and output components
X = array[:,0:4]
Y = array[:,4]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
# summarize transformed data
numpy.set_printoptions(precision=3)
print(rescaledX[0:5,:])




[[ 0.222  0.625  0.068  0.042]
 [ 0.167  0.417  0.068  0.042]
 [ 0.111  0.5    0.051  0.042]
 [ 0.083  0.458  0.085  0.042]
 [ 0.194  0.667  0.068  0.042]]


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
##### Normalize Data

def norm_data(COLS = 20):
    # Set this as True if you want to normalize the data, set False otherwise.
    data_normalization = True
    
    if data_normalization:
        # Normalization of Input Data.
        mean = []
        std = []
        
        # Calculation of mean and standard deviation for all input variables.
        for i in range(0,COLS-1):
            X[i] = np.array(X[i])
            mean.append(np.mean(X[i]))
            std.append(np.std(X[i]))
    
        # Returning Normalized Data
        return [np.array([(X[i] - mean[i])/(std[i]) for i in range(0,20)]),np.array(Y),mean,std]
    else:
        return [np.array(X),np.array(Y)]
    print(normalizedX[0:5,:])


In [ ]:
# Defining a function which calculates euclidean distance between two data points
def euclideanDistance(data1, data2, length):
    distance = 0
    for x in range(length):
        distance += np.square(data1[x] - data2[x])
    return np.sqrt(distance)



In [ ]:
# Defining our KNN model
def knn(trainingSet, testInstance, k):
 
    distances = {}
    sort = {}
 
    length = testInstance.shape[1]

In [ ]:
#### Start of STEP 3
    # Calculating euclidean distance between each row of training data and test data
    for x in range(len(trainingSet)):
        
        #### Start of STEP 3.1
        dist = euclideanDistance(testInstance, trainingSet.iloc[x], length)

        distances[x] = dist[0]
        #### End of STEP 3.1

In [ ]:
 #### Start of STEP 3.2
    # Sorting them on the basis of distance
    sorted_d = sorted(distances.items(), key=operator.itemgetter(1))
    #### End of STEP 3.2
 
    neighbors = []
    
    #### Start of STEP 3.3
    # Extracting top k neighbors
    for x in range(k):
        neighbors.append(sorted_d[x][0])
    #### End of STEP 3.3
    classVotes = {}

In [ ]:
#### Start of STEP 3.4
    # Calculating the most freq class in the neighbors
    for x in range(len(neighbors)):
        response = trainingSet.iloc[neighbors[x]][-1]
 
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    #### End of STEP 3.4

    #### Start of STEP 3.5
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return(sortedVotes[0][0], neighbors)
    #### End of STEP 3.5
